### ISSUE TITLE
Opracować i zaimplementować DAG do analizy sentymentu 

### ISSUE THREAD

**Issue by dominik-air** [dominik-air/sentiment-analysis-pipeline#4]
Powinien składać się z trzech etapów (ale można się wykazać ambicjami):
1. Załadowanie tekstu tweetow z Postgresql
2. Dokonanie analizy sentymentu przy pomocy[ modelu z HuggingFace](https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest?text=Covid+cases+are+increasing+fast%21)
3. Zapisanie wyników do bazy danych

Poki co moze po prostu czytać dane z jakiegoś pliku i zapisywać wyniki do csv o następującej strukturze:
id; tweet_id;positive;negative;neutral;
1;1;0.5;0.3;0.2;

**Comment by niziox** [comment]
Done, the model is working correctly.
